a=input("Enter the first name:")
b=input("Enter the second name:")
c=int(input("Enter the marl 1:"))
d=int(input("Enter the mark 2:"))
e=int(input("Enter the mark 3:"))
print("The name is:",a+" "+b )
print("The marks are:",c+d+e)
print("The average marks of 3 subject is:",(c+d+e)/3)